matrix:
    include:
        - os: linux
          language: python
          python:
            - "2.6"
            - "2.7"
            - "3.2"
            - "3.3"
            - "3.4"
            - "3.5"
            - "3.6"
          sudo: true
          dist: trusty
          group: edge
          before_install: sudo apt install python-pip
        - os: osx
          before_install:
            - sudo easy_install pip
            - sudo -H pip install --upgrade pip
install:
  - pip install virtualenv
  - ./setup
script:
  - ./telemetry &
  - sleep 2
  - wget http://localhost:5001